import { ChakraProvider } from "@chakra-ui/react";
import { Provider } from "react-redux";

import store from "./store";
import "./globals.css";
import App from "./components/App";

export const metadata = {
  title: "Todoshka",
  description: "Generated by Serafim",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChakraProvider>
        {/* <Provider store={store}> */}
        <body>{children}</body>
        {/* </Provider> */}
      </ChakraProvider>
    </html>
  );
}
